<script type="text/javascript" src="<?php echo $this->bootstrapJS ?>"></script>
<link rel="stylesheet" href="<?php echo $this->bootstrapCSS ?>" />

<style>
    body{background-color: #7F7F7F!important}

    #lw_fe_inputelement_lw_formular_template{width: 800px;height: 600px;}
    #tabs ul li a{color: #fff;}

    .activeline {background: #e8f2ff !important;}

    .active{background-color: #777;}

    .description {
        margin-bottom:60px;
        border:1px solid #aaa;
        border-radius: 5px;
        background-color:#eee;
        padding:10px;
    }

    legend.lwadminform {
        height: 20px;
        margin-bottom: 2px;
        line-height: 20px;
        width: 310px;
    }
    html body div#lwContent div {
        font-size: 12px!important;
    }

    fieldset.lwadminform {
        position: relative;
    }


    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center form#gotoform input#gotoid {
        width: 45px;
        margin-bottom: 0;
    }
    html body div#lwLeftnavi div#lwPageTreeNav.lwBoxLeftContent center {
        height: 35px;
    }    


    #container_plugin_bionrw_news{
        background-color: #fff;
        border: 1px solid #bbb;
        border-radius: 10px;
        padding: 10px;
    }

    #container_plugin_bionrw_news #myform .control-group input{
        height: 30px;
        width: 50px;
    }
    #container_plugin_bionrw_news #myform .control-group select{width: 330px;}

    <?php if ($this->teaserview): ?>
        #teaseroptions{display: block;}
    <?php else: ?>
        #teaseroptions{display: none;}
    <?php endif;?>
    
</style>

<fieldset class="lwadminform">

    <legend class="lwadminform">lw_page_guest_comments Basisdaten bearbeiten</legend>
    <div id="container_plugin_bionrw_news">
        <br>

        <form id="myform" action="<?php echo $this->actionUrl ?>" method="POST" class="form-horizontal">

            <div class="control-group">
                <label class="control-label" for="language">Sprache</label>
                <div class="controls">
                    <select id="language" name="language">
                        <option value="de" <?php if ($this->language == "de"): ?>selected="selected"<?php endif; ?>>Deutsch</option>
                        <option value="en" <?php if ($this->language == "en"): ?>selected="selected"<?php endif; ?>>Englisch</option>
                    </select>
                </div>
            </div>

            <div style="margin-top:15px;margin-bottom:20px; margin-left:20px;">
                <input class="btn btn-primary" type="submit" value="speichern" onClick="submitForm()" />&nbsp;<input class="btn" type="button" value="abbrechen" onclick="document.location.href = '?obj=content';"/>
            </div>
        </form>
    </div>
</fieldset>